import React, { useContext, useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Box, CircularProgress, Container, Grid } from "@mui/material";
import Hero from "../../components/Hero/Hero";
import ProductCard from "../../components/ProductCard/ProductCard";
import { ProductContext } from "../../context/ProductsContext";
import styles from "../../styles/Home.module.css";

const HomeScreen = () => {
  // const [products, setProducts] = useState([]);
  const { products, getAllProducts } = useContext(ProductContext);

  // const getAllProducts = async () => {
  //   const allproducts = await (await fetch("/api/products")).json();
  //   setProducts(allproducts);
  // };

  useEffect(() => {
    getAllProducts("/api/products");
  }, []);

  console.log(products);

  return (
    <div className={styles.container}>
      <Head>
        <title>Hashtag Store PK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <Container maxWidth="lg">
          <Grid container>
            {products.length === 0 ? (
              <Box
                sx={{
                  display: "flex",
                  margin: "0 auto",
                }}
              >
                <CircularProgress color="primary" />
              </Box>
            ) : (
              products.map((product, index) => (
                <Grid key={`products-${index}`} item md={3}>
                  <ProductCard product={product} />
                </Grid>
              ))
            )}
          </Grid>
        </Container>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default HomeScreen;
