import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero/Hero";
import styles from "../styles/Home.module.css";

export default function Home() {
  const helloHandler = async (e) => {
    e.preventDefault();
    const responseData = await (await fetch("/api/hello")).json();
    console.log(responseData);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Hashtag Store PK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
